[book]
title = "Ox"
authors = ["kcza"]
description = "Documentation for Ox"
language = "en"
multilingual = false
src = "src"

[build]
create-missing = false

[output.html]
additional-css = ['theme/css/style.css', 'theme/css/mermaid.css']
cname = "kcza.net"
copy-fonts = true
default-theme = "ayu"
edit-url-template = "https://github.com/TheSignPainter98/ox/blob/master/docs/{path}"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/TheSignPainter98/ox"
preferred-dark-theme = "ayu"
site-url = "/ox/"
smart-punctuation = true
additional-js = ["theme/js/mermaid.min.js", "theme/js/mermaid-init.js"]

[output.html.font]
enable = true
truetype = true
ttc = true
ttf = true
woff = true

[output.html.fold]
enable = true

[output.linkcheck]

[preprocessor.ox]
command = "docs/mdbook-ox/target/release/mdbook-ox"

[preprocessor.mermaid]

[preprocessor.diataxis]

[preprocessor.diataxis.compass.tutorials]
description = "Hands-on lessons in using ox"

[preprocessor.diataxis.compass.reference]
title = "Reference materials"
description = "Technical information about ox"
