[book]
title = "Freight"
authors = ["kcza"]
description = "Documentation for Freight"
language = "en"
multilingual = false
src = "src"

[build]
create-missing = false

[output.html]
additional-css = ['theme/css/style.css']
cname = "kcza.net"
copy-fonts = true
default-theme = "ayu"
edit-url-template = "https://github.com/TheSignPainter98/freight/blob/master/docs/{path}"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/TheSignPainter98/freight"
preferred-dark-theme = "ayu"
site-url = "/freight/"
smart-punctuation = true
additional-js = ["theme/js/mermaid.min.js", "theme/js/mermaid-init.js"]

[output.html.font]
enable = true
truetype = true
ttc = true
ttf = true
woff = true

[output.html.fold]
enable = true

[output.linkcheck]

[preprocessor.mermaid]

[preprocessor.diataxis.compass.tutorials]
description = "Hands-on lessons in freighting"

[preprocessor.diataxis.compass.reference]
title = "Reference materials"
description = "Technical information about freight"
