[book]
title = "Shunt"
authors = ["kcza"]
description = "Documentation for Shunt"
language = "en"
multilingual = false
src = "src"

[build]
create-missing = false

[output.html]
additional-css = [
  'theme/css/style.css',
  'theme/css/mermaid.css',
  'theme/highlight.js',
]
cname = "kcza.net"
copy-fonts = true
default-theme = "ayu"
edit-url-template = "https://github.com/TheSignPainter98/shunt/blob/master/docs/{path}"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/TheSignPainter98/shunt"
preferred-dark-theme = "ayu"
site-url = "/shunt/"
smart-punctuation = true
additional-js = ["theme/js/mermaid.min.js", "theme/js/mermaid-init.js"]

[output.html.font]
enable = true
truetype = true
ttc = true
ttf = true
woff = true

[output.html.fold]
enable = true

[output.linkcheck]

[preprocessor.shunt]
command = "docs/mdbook-shunt/target/release/mdbook-shunt"

[preprocessor.mermaid]

[preprocessor.diataxis]

[preprocessor.diataxis.compass.tutorials]
description = "Hands-on lessons in using shunt"

[preprocessor.diataxis.compass.reference]
title = "Reference materials"
description = "Technical information about shunt"
